TOP=../..
include $(TOP)/configure/CONFIG

#DB += exercise1.db
#DB += exercise2.db
#DB += exercise3.db
#DB += exercise4Top.db
#DB += exercise4a.db
#DB += exercise5.db
#DB += exercise6.db
#DB += exercise7.db
#DB += exercise8.db
DB += motorTest.db
#DB += ioTest.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
